### ISSUE TITLE
Minor: window resizing lags

### ISSUE THREAD

**Issue by JPHutchins** [nickbeth/wsl-usb-manager#4]
If it's a side effect of the framework then I think it would be OK to simply disabled window resizing outright.

**Comment by nickbeth** [comment]
I've looked into this in the past, this is sadly combined fault of the Win32 API and the Rust library, and is highly dependent on current CPU clock speed from my testing. Enabling higher boost clocks via a higher power profile makes the issue less apparent. This is not something I can fix without rewriting the entire app.
